import test from "node:test";
import assert from "node:assert/strict";
import { assignFormExperimentArm } from "./experiment-assignment";
import { chooseWeightedOutcome, incentiveGrantIsClaimable } from "./incentive-logic";
import { consentRequestEvidence } from "./consent-evidence";
import { consentPreset } from "./consent-presets";
import { shouldSuppressKnownCustomerIncentive } from "./acquisition-policy";

test("experiment assignment is deterministic",()=>assert.equal(assignFormExperimentArm({experimentId:"e",assignmentSalt:"s",visitorId:"v",controlRatio:.1,splitRatio:.5}),assignFormExperimentArm({experimentId:"e",assignmentSalt:"s",visitorId:"v",controlRatio:.1,splitRatio:.5})));
test("experiment assignment returns only valid arms",()=>{for(let i=0;i<100;i++)assert.ok(["CONTROL","A","B"].includes(assignFormExperimentArm({experimentId:"e",assignmentSalt:"s",visitorId:String(i),controlRatio:.1,splitRatio:.5})))});
test("zero control produces treatment arms",()=>{for(let i=0;i<50;i++)assert.notEqual(assignFormExperimentArm({experimentId:"e",assignmentSalt:"s",visitorId:String(i),controlRatio:0,splitRatio:.5}),"CONTROL")});
test("weighted boundary selects first outcome",()=>assert.equal(chooseWeightedOutcome([{label:"a",weight:2,discountValue:1},{label:"b",weight:1,discountValue:0}],0).label,"a"));
test("weighted boundary selects last outcome",()=>assert.equal(chooseWeightedOutcome([{label:"a",weight:2,discountValue:1},{label:"b",weight:1,discountValue:0}],2).label,"b"));
test("weighted outcomes reject one option",()=>assert.throws(()=>chooseWeightedOutcome([{label:"a",weight:1}],0)));
test("weighted outcomes reject nonpositive weights",()=>assert.throws(()=>chooseWeightedOutcome([{label:"a",weight:0},{label:"b",weight:1}],0)));
test("EU preset requires double opt in",()=>assert.equal(consentPreset("eu_uk").doubleOptInEmail,true));
test("US preset permits single opt in",()=>assert.equal(consentPreset("us").doubleOptInEmail,false));
test("unknown market falls back conservatively",()=>assert.equal(consentPreset("unknown").version,"global-conservative-v2"));
test("known subscriber incentives are suppressed",()=>assert.equal(shouldSuppressKnownCustomerIncentive({isNewSubscriber:false,hasRecentOrder:false}).reason,"already_subscribed"));
test("recent-buyer incentives are suppressed",()=>assert.equal(shouldSuppressKnownCustomerIncentive({isNewSubscriber:true,hasRecentOrder:true}).reason,"recent_customer"));
test("explicit merchant override permits known buyers",()=>assert.equal(shouldSuppressKnownCustomerIncentive({isNewSubscriber:false,hasRecentOrder:true,allowKnownCustomers:true}).allowed,true));
test("network consent evidence hashes IP rather than retaining it",()=>{const evidence=consentRequestEvidence({ip:"203.0.113.7",userAgent:"browser",secret:"test-secret"});assert.equal("ip" in evidence,false);assert.equal(evidence.ipHash?.length,64);assert.equal(evidence.userAgent,"browser")});
test("failed and stale incentive grants are retryable",()=>{const now=new Date("2026-09-07T12:00:00Z");assert.equal(incentiveGrantIsClaimable("failed",now,now),true);assert.equal(incentiveGrantIsClaimable("processing",new Date(now.getTime()-301000),now),true);assert.equal(incentiveGrantIsClaimable("processing",now,now),false)});
