import { prisma } from "@allohq/database";
import { send } from "@allohq/messaging";
import type { BriefingContent } from "./types";

interface DeliveryPreferences {
  channel: "email" | "whatsapp" | "in_app";
  email?: string;
  phone?: string;
}

/**
 * Deliver a briefing to the merchant via their preferred channel.
 * Falls back to in-app only if no contact info available.
 */
export async function deliverBriefing(
  briefingId: string,
  _storeId: string,
  preferences?: DeliveryPreferences,
): Promise<{ delivered: boolean; channel: string; error?: string }> {
  const briefing = await prisma.merchantBriefing.findUnique({
    where: { id: briefingId },
  });

  if (!briefing) {
    return { delivered: false, channel: "none", error: "Briefing not found" };
  }

  const content = briefing.content as unknown as BriefingContent;
  const channel = preferences?.channel ?? "in_app";

  // In-app delivery: just mark as delivered, UI will poll via API
  if (channel === "in_app") {
    await prisma.merchantBriefing.update({
      where: { id: briefingId },
      data: { deliveredVia: "in_app" },
    });
    return { delivered: true, channel: "in_app" };
  }

  // Email delivery
  if (channel === "email" && preferences?.email) {
    const summaryText = formatBriefingForEmail(content);
    try {
      await send({
        channel: "email",
        to: preferences.email,
        subject: `${content.title} — Joon Intelligence`,
        html: summaryText,
      });
      await prisma.merchantBriefing.update({
        where: { id: briefingId },
        data: { deliveredVia: "email" },
      });
      return { delivered: true, channel: "email" };
    } catch (err) {
      return { delivered: false, channel: "email", error: (err as Error).message };
    }
  }

  // WhatsApp delivery
  if (channel === "whatsapp" && preferences?.phone) {
    const summaryText = formatBriefingForWhatsApp(content);
    try {
      await send({
        channel: "whatsapp",
        to: preferences.phone,
        body: summaryText,
      });
      await prisma.merchantBriefing.update({
        where: { id: briefingId },
        data: { deliveredVia: "whatsapp" },
      });
      return { delivered: true, channel: "whatsapp" };
    } catch (err) {
      return { delivered: false, channel: "whatsapp", error: (err as Error).message };
    }
  }

  // Fallback to in-app
  await prisma.merchantBriefing.update({
    where: { id: briefingId },
    data: { deliveredVia: "in_app" },
  });
  return { delivered: true, channel: "in_app" };
}

/**
 * Get merchant's notification preferences for a store.
 */
export async function getNotificationPreferences(
  storeId: string,
): Promise<DeliveryPreferences> {
  // Look up the store owner's contact info
  const store = await prisma.store.findUnique({
    where: { id: storeId },
    include: {
      workspace: {
        include: {
          members: {
            where: { role: "admin" },
            take: 1,
            include: { user: true },
          },
        },
      },
    },
  });

  const adminUser = store?.workspace?.members[0]?.user;

  if (adminUser?.email) {
    return { channel: "email", email: adminUser.email };
  }

  return { channel: "in_app" };
}

/** Format briefing content as HTML email */
function formatBriefingForEmail(content: BriefingContent): string {
  let html = `<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">`;
  html += `<h1 style="font-size: 24px; color: #1A1A1A;">${content.title}</h1>`;
  html += `<p style="color: #666; font-size: 16px;">${content.summary}</p>`;

  for (const section of content.sections) {
    html += `<h2 style="font-size: 18px; color: #1A1A1A; border-bottom: 1px solid #EEE; padding-bottom: 8px;">${section.heading}</h2>`;
    html += `<ul style="padding-left: 16px;">`;
    for (const item of section.items) {
      html += `<li style="margin-bottom: 8px; color: #333;">`;
      html += item.text;
      if (item.metric) {
        html += ` <strong>${item.metric.value}</strong>`;
        if (item.metric.change) {
          const color = item.metric.trend === "up" ? "#16A34A" : item.metric.trend === "down" ? "#DC2626" : "#666";
          html += ` <span style="color: ${color};">(${item.metric.change})</span>`;
        }
      }
      html += `</li>`;
    }
    html += `</ul>`;
  }

  html += `<p style="color: #999; font-size: 12px; margin-top: 24px;">Generated by Joon Intelligence</p>`;
  html += `</div>`;
  return html;
}

/** Format briefing content as WhatsApp text message */
function formatBriefingForWhatsApp(content: BriefingContent): string {
  let text = `*${content.title}*\n${content.summary}\n\n`;

  for (const section of content.sections) {
    text += `*${section.heading}*\n`;
    for (const item of section.items) {
      text += `• ${item.text}`;
      if (item.metric) {
        text += ` — ${item.metric.value}`;
        if (item.metric.change) text += ` (${item.metric.change})`;
      }
      text += `\n`;
    }
    text += `\n`;
  }

  return text.trim();
}
