export { generateEmail } from "./generate-email";
export type { GenerateEmailInput, GenerateEmailOutput, CreativeIntensity, BrandSettings } from "./generate-email";
export { generateWhatsApp } from "./generate-whatsapp";
export type { GenerateWhatsAppInput, GenerateWhatsAppOutput } from "./generate-whatsapp";
export { generateSms } from "./generate-sms";
export type { GenerateSmsInput, GenerateSmsOutput } from "./generate-sms";
export { generateRcs } from "./generate-rcs";
export type { GenerateRcsInput, GenerateRcsOutput, RcsAction } from "./generate-rcs";
export { brandVoiceBlock, intentInstructions, formatProductsForPrompt } from "./prompt-templates";
export { LAYOUT_TEMPLATES, getLayoutById } from "./layout-templates";
export type { LayoutTemplate } from "./layout-templates";
