import type { ConnectionOptions } from "bullmq";

/** Redis connection used by all queues and workers */
export const redisConnection: ConnectionOptions = {
  host: process.env["REDIS_HOST"] ?? "localhost",
  port: Number(process.env["REDIS_PORT"] ?? 6379),
  password: process.env["REDIS_PASSWORD"],
};

/** Queue name constants */
export const QUEUE_NAMES = {
  SYNC: "sync",
  RFM: "rfm",
  LTV: "ltv",
  EMAIL_SEND: "email-send",
  SHOPIFY_WEBHOOK: "shopify-webhook",
  BRAND_ANALYSIS: "brand-analysis",
  AUTOMATION_GENERATE: "automation-generate",
  AGENT_PIPELINE: "agent-pipeline",
  AUTOMATION_TRIGGER: "automation-trigger",
  TRIGGER_CHECK: "trigger-check",
  EMBEDDING: "embedding",
  AGENT_OBSERVE: "agent-observe",
  CONVERSATION_PROCESS: "conversation-process",
  ABANDONED_CART_CHECK: "abandoned-cart-check",
  SEGMENT_CHANGE: "segment-change",
  CUSTOMER_STATE: "customer-state",
  GUARDRAIL_CHECK: "guardrail-check",
  BRAND_KIT: "brand-kit",
  PRODUCT_IMAGE: "product-image",
  CREATIVE_GEN: "creative-gen",
  OPPORTUNITY_SCAN: "opportunity-scan",
  CAMPAIGN_FACTORY: "campaign-factory",
  PRODUCT_CYCLES: "product-cycles",
  MERCHANT_BRIEFING: "merchant-briefing",
  BASELINE: "baseline",
  WEEKLY_REPORT: "weekly-report",
  JOURNEY_STEP: "journey-step",
  AB_TEST: "ab-test",
  REVENUE_FORECAST: "revenue-forecast",
  PRODUCT_RECOMMENDATION: "product-recommendation",
  SHIPPING_UPDATE: "shipping-update",
  RESTOCK_ALERT: "restock-alert",
  PRICE_DROP: "price-drop",
  REPURCHASE_REMINDER: "repurchase-reminder",
  INVENTORY_MONITOR: "inventory-monitor",
  STORE_ACTIVATION: "store-activation",
  OUTCOME_ATTRIBUTION: "outcome-attribution",
  CHURN_INTERVENTION: "churn-intervention",
  BENCHMARK_AGGREGATE: "benchmark-aggregate",
  CUSTOMER_VOICE: "customer-voice",
  MEMORY_WRITER: "memory-writer",
  DAILY_REVENUE_EMAIL: "daily-revenue-email",
  OVERNIGHT_OPS: "overnight-ops",
  EVENT_REACT: "event-react",
  BROWSE_ABANDONMENT: "browse-abandonment",
  COPY_LEARNER: "copy-learner",
  BASKET_ANALYSIS: "basket-analysis",
  PRODUCT_SEGMENTS: "product-segments",
  PRIVACY_RETENTION: "privacy-retention",
} as const;
