/**
 * The v1 release boundary, enforced server-side.
 *
 * docs/v1-release-boundary.md defines Joon v1 as a free Shopify app for
 * EMAIL campaigns and merchant-approved EMAIL automations with mandatory human
 * approval and default randomized holdouts. Everything outside that contract
 * must FAIL CLOSED — hiding
 * navigation is not sufficient, because background workers and API routes can
 * still act on their own (two campaign drafts and a merchant summary email were
 * generated by scheduled workers on 2026-08-10, with the UI never involved).
 *
 * This module is the single source of truth for that boundary. It has no
 * dependencies and no I/O so it can be imported from workers, api and web.
 */

/** Capabilities that exist in the codebase but are OUTSIDE the v1 contract. */
export const V1_BLOCKED_CAPABILITIES = [
  /** Autonomy tiers / auto-execution of approved-by-nobody actions. */
  "autopilot",
  /** Activation or mutation of an automation without merchant approval. */
  "unapproved_automation_activation",
  /** Proactive outreach: opportunity scans, overnight ops, agent observation. */
  "proactive_outreach",
  /** Journey nodes that deliver through anything except email. */
  "non_email_journey_nodes",
  /** Churn interventions (send on their own). */
  "churn_intervention",
  /** Scheduled outbound emails TO THE MERCHANT (daily/weekly digests). */
  "merchant_emails",
  /** Background analysis jobs not required to draft a one-off campaign. */
  "background_analysis",
  /** Cross-brand benchmark aggregation. */
  "cross_brand_benchmarks",
  /** Non-email delivery channels. */
  "non_email_channels",
  /** Performance-fee billing surfaces. */
  "performance_billing",
] as const;

export type V1BlockedCapability = (typeof V1_BLOCKED_CAPABILITIES)[number];

/** Delivery channels permitted in v1. */
export const V1_ALLOWED_CHANNELS = ["email"] as const;

export const V1_ALLOWED_AUTOMATION_NODE_TYPES = [
  "send_email",
  "wait",
  "condition",
  "silence_check",
] as const;

export interface AutomationReleaseShape {
  nodes?: unknown;
  smsTemplateIds?: string[];
  whatsappTemplateIds?: string[];
  rcsTemplateIds?: string[];
}

export function findV1AutomationViolations(
  automation: AutomationReleaseShape,
  releaseMode: string | undefined = process.env["V1_RELEASE_MODE"],
): string[] {
  if (!isV1ReleaseMode(releaseMode)) return [];
  const violations: string[] = [];
  if (automation.smsTemplateIds?.length) violations.push("sms templates");
  if (automation.whatsappTemplateIds?.length) violations.push("WhatsApp templates");
  if (automation.rcsTemplateIds?.length) violations.push("RCS templates");
  const nodes = Array.isArray(automation.nodes) ? automation.nodes : [];
  for (const node of nodes) {
    const type = node && typeof node === "object"
      ? (node as { type?: unknown }).type
      : undefined;
    if (
      typeof type !== "string" ||
      !(V1_ALLOWED_AUTOMATION_NODE_TYPES as readonly string[]).includes(type)
    ) {
      violations.push(`workflow node: ${String(type ?? "invalid")}`);
    }
  }
  return [...new Set(violations)];
}

export function assertV1EmailAutomation(
  automation: AutomationReleaseShape,
  releaseMode: string | undefined = process.env["V1_RELEASE_MODE"],
): void {
  const violations = findV1AutomationViolations(automation, releaseMode);
  if (violations.length) {
    throw new ReleaseBoundaryError(
      "non_email_journey_nodes",
      violations.join(", "),
    );
  }
}

/**
 * True when the v1 boundary is being enforced.
 *
 * FAIL CLOSED: the boundary is active unless something explicitly opts out with
 * V1_RELEASE_MODE="false". An unset, empty, misspelled or malformed value keeps
 * the restrictions on, so a missing env var can never widen what the server does.
 */
export function isV1ReleaseMode(
  value: string | undefined = process.env["V1_RELEASE_MODE"],
): boolean {
  return value?.trim().toLowerCase() !== "false";
}

/** Thrown when a caller attempts something outside the v1 contract. */
export class ReleaseBoundaryError extends Error {
  readonly capability: string;
  readonly code = "V1_RELEASE_BOUNDARY" as const;

  constructor(capability: string, detail?: string) {
    super(
      `Blocked by the v1 release boundary: ${capability}${detail ? ` (${detail})` : ""}. ` +
        `See docs/v1-release-boundary.md.`,
    );
    this.name = "ReleaseBoundaryError";
    this.capability = capability;
  }
}

/** Is this capability permitted under the current release mode? */
export function isCapabilityAllowed(
  capability: V1BlockedCapability,
  releaseMode: string | undefined = process.env["V1_RELEASE_MODE"],
): boolean {
  if (!isV1ReleaseMode(releaseMode)) return true;
  return !V1_BLOCKED_CAPABILITIES.includes(capability);
}

/** Throw unless the capability is permitted. Use at points of effect. */
export function assertCapabilityAllowed(
  capability: V1BlockedCapability,
  detail?: string,
  releaseMode: string | undefined = process.env["V1_RELEASE_MODE"],
): void {
  if (!isCapabilityAllowed(capability, releaseMode)) {
    throw new ReleaseBoundaryError(capability, detail);
  }
}

/** Is this delivery channel permitted? v1 is email-only. */
export function isChannelAllowed(
  channel: string,
  releaseMode: string | undefined = process.env["V1_RELEASE_MODE"],
): boolean {
  if (!isV1ReleaseMode(releaseMode)) return true;
  return (V1_ALLOWED_CHANNELS as readonly string[]).includes(
    channel.trim().toLowerCase(),
  );
}

/** Throw unless the channel is permitted. Use at the send chokepoint. */
export function assertChannelAllowed(
  channel: string,
  detail?: string,
  releaseMode: string | undefined = process.env["V1_RELEASE_MODE"],
): void {
  if (!isChannelAllowed(channel, releaseMode)) {
    throw new ReleaseBoundaryError(
      "non_email_channels",
      detail ? `${channel}: ${detail}` : channel,
    );
  }
}

/**
 * Repeatable BullMQ schedules, mapped to the capability they serve.
 *
 * IMPORTANT: these ids are persisted in Redis by upsertJobScheduler. Declining
 * to register one at boot does NOT stop it — a schedule written by an earlier
 * release keeps firing until it is explicitly removed. Callers must REMOVE the
 * blocked ids, not merely skip them.
 *
 * `null` marks a schedule that is inside the v1 contract and must keep running.
 */
export const SCHEDULE_CAPABILITIES: Record<string, V1BlockedCapability | null> = {
  // --- inside v1: treatment/control reporting + customer state upkeep -------
  "outcome-attribution-schedule": null,
  "state-decay-schedule": null,
  "privacy-retention-schedule": null,

  // --- outside v1 -----------------------------------------------------------
  "trigger-check-schedule": null,
  "abandoned-cart-check-schedule": null,
  // These legacy scanners do not execute a merchant-approved AutomationVersion.
  "repurchase-reminder-schedule": "proactive_outreach",
  "browse-abandonment-schedule": "proactive_outreach",
  "inventory-monitor-schedule": "proactive_outreach",
  // Safe v1 intelligence: this scanner only creates approval-queue drafts. It
  // never activates a campaign or touches a messaging provider.
  "opportunity-scan-schedule": null,
  "overnight-ops-schedule": "proactive_outreach",
  "agent-observe-schedule": "proactive_outreach",
  "churn-intervention-schedule": "churn_intervention",
  "daily-briefing-schedule": "merchant_emails",
  "weekly-report-schedule": "merchant_emails",
  "daily-revenue-summary-schedule": "merchant_emails",
  "daily-revenue-email-schedule": "merchant_emails",
  "customer-voice-schedule": "merchant_emails",
  "product-cycles-schedule": "background_analysis",
  "ab-test-evaluation-schedule": "background_analysis",
  "send-time-optimization-schedule": "background_analysis",
  "revenue-forecast-schedule": "background_analysis",
  "product-recommendation-affinity-schedule": "background_analysis",
  "copy-learner-schedule": "background_analysis",
  "basket-analysis-schedule": "background_analysis",
  // Category/affinity segments are read-only analysis and are useful from the
  // first RFM run onward. They cannot dispatch messages.
  "product-segments-schedule": null,
  "benchmark-aggregate-schedule": "cross_brand_benchmarks",
};

/** Should this schedule be registered under the current release mode? */
export function isScheduleAllowed(
  scheduleId: string,
  releaseMode: string | undefined = process.env["V1_RELEASE_MODE"],
): boolean {
  const capability = SCHEDULE_CAPABILITIES[scheduleId];
  // Unknown ids fail closed under v1: a new schedule must be classified here
  // before it is allowed to run.
  if (capability === undefined) return !isV1ReleaseMode(releaseMode);
  if (capability === null) return true;
  return isCapabilityAllowed(capability, releaseMode);
}
